--- #YAML:1.0
name:               File-Vctools
version:            0.07
abstract:           Compare different versions of text files and identify changes
author:
    - Klaus Eichner <klaus03@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Diff:  1.1902
    File::Slurp:      9999.12
    XML::Reader:      0.37
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
